### ISSUE TITLE
Kinetic Spear disappears on save

### ISSUE THREAD

**Issue by deng-tianhan** [NosVladimir/KineticArchetypes#10]
After playing more I noticed it consistently disappears on save (in Crusader's camp map at least)

>[9971.3952 - System]: Saving to C:/Users/xxx/AppData/LocalLow/Owlcat Games/Pathfinder Wrath Of The Righteous\Saved Games\Manual_16_Camp.zks
[9971.5424 - Mods]: KineticArchetypes: Overriding visual for kinetic blade of True into [BlueprintItemWeapon: ColdIronLongspear]
[9971.9918 - History.System]: Game saved on version 2.1.4w
[9971.9918 - System]: Begin threaded save
[9971.9918 - System]: SerializeAndSaveThread: started
[9972.6273 - System]: Finished wait for threaded save
[9972.6393 - Default]: Can't insert kineticist blade to main hand
Owlcat.Runtime.Core.Logging.Logger.Owlcat.Runtime.Core.Logging.Logger.Log_Patch0(Owlcat.Runtime.Core.Logging.Logger,Owlcat.Runtime.Core.Logging.LogChannel,System.Object,Owlcat.Runtime.Core.Logging.LogSeverity,System.Exception,System.Object,System.Object[]) (at :0)
Kingmaker.UnitLogic.Class.Kineticist.AddKineticistBlade.Kingmaker.UnitLogic.Class.Kineticist.AddKineticistBlade.OnActivate_Patch1(Kingmaker.UnitLogic.Class.Kineticist.AddKineticistBlade) (at :0)

I tried to reset visual while empty handed. The spear disappear problem remains.

Tested on the latest release build

**Comment by deng-tianhan** [comment]
I didn't notice this issue when using the old build which had the buff version of spear.

Now that whip AOOs are fixed, maybe can consider changing spear back to the initial implementation?

**Comment by deng-tianhan** [comment]
BTW, I just wanted to say: really appreciate the time and effort you and other mod authors have put in. I realize it's not easy to mod with so many limitations and buggy code from the base game...

**Comment by NosVladimir** [comment]
Can you try the new release v1.0.1 and see if the problem remains?

**Comment by deng-tianhan** [comment]
Tested v1.0.1 fixed the problem
