### ISSUE TITLE
Not working in recent update

### ISSUE THREAD

**Issue by rkorpo** [NosVladimir/KineticArchetypes#17]
Hi,

After Lord of Nothing DLC update I don't see any of the archetypes on the available list. Can you please take a look?

**Comment by NosVladimir** [comment]
Thanks for reporting. It's likely the update has broken the mod, I'll take a look asap

**Comment by NosVladimir** [comment]
I've updated the mod yesterday, tested without other mods and it's working fine. Could you also check if it's working?
