### ISSUE TITLE
Compatability issue

### ISSUE THREAD

**Issue by StoyanKucarov** [NosVladimir/KineticArchetypes#18]
Noticed the game doesn't load if the mod is used with swashbuckler or prestigeplus

**Comment by NosVladimir** [comment]
I'll have a look, at the latest by the weekend

**Comment by NosVladimir** [comment]
Just tested, I have the two mods swashbuckler and prestigeplus both at the newest version, and the game runs fine. Could you update the mods and see if the issue is still around?
