### ISSUE TITLE
Normal kineticist fire blasts like onslaught blaster

### ISSUE THREAD

**Issue by Kosha99** [NosVladimir/KineticArchetypes#21]
When I have companion with onslaught blaster archetype any other kineticist fire multiple full damage blasts.

Tested on v2.2.4p
Toybox 1.5.9
Tabletop Tweaks Core 0.7.1
Kinetic Archetype 1.1.4

**Comment by NosVladimir** [comment]
Thanks for reporting this bug. I'm currently having a holiday now and will look at this when I'm back in late Feb

**Comment by NosVladimir** [comment]
Fixed in [v1.1.5](https://github.com/NosVladimir/KineticArchetypes/releases/tag/v1.1.5)
