### ISSUE TITLE
Fighter's Finesse

### ISSUE THREAD

**Issue by Kosha99** [NosVladimir/KineticArchetypes#22]
Fighter's finesse feat broken.
![Screenshot_4](https://github.com/NosVladimir/KineticArchetypes/assets/159198610/bca0e4ae-90c6-4ade-830c-0965726b5813)

**Comment by NosVladimir** [comment]
Hi, I'm not sure if this is related to this mod?

**Comment by Kosha99** [comment]
Disabling this mod solves the problem. Maybe this is something related to esoteric blade unique weapon training category?

**Comment by NosVladimir** [comment]
Thanks, this might be related to another issue that broke advanced weapon training. I'll take a look by the weekend

**Comment by NosVladimir** [comment]
Fixed in [v1.1.5](https://github.com/NosVladimir/KineticArchetypes/releases/tag/v1.1.5)
