### ISSUE TITLE
Suggestion: change blade shape apply to offhand as well

### ISSUE THREAD

**Issue by deng-tianhan** [NosVladimir/KineticArchetypes#5]
Currently change blade shape only applies to mainhand, not offhand (duelist)

**Comment by NosVladimir** [comment]
That's strange, it should already work with offhance kinetic blade. Could you provide a screenshot, as well as the game's log file at C:\Users\<Username>\AppData\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous\GameLogFull.txt?

**Comment by deng-tianhan** [comment]
![image](https://github.com/NosVladimir/KineticArchetypes/assets/24478731/63a54298-3523-44b2-aea0-56b73a6095cb)

main hand changed to longsword, off hand didn't work.

not able to provide the full logs as it became littered with unrelated warning messages from other mods... will try and see if I can get a cleaner version

**Comment by NosVladimir** [comment]
Providing the full log is fine, I can search for any error messages generated by this mod.

I don't see the little blue eye icon that should appear in the bottom-left corner of the blade icon, just like how normal weapons can be transmogged by the gold golem. Also the kinetic blade's particle effects are missing. This means the transmogging function for the kinetic blades is misbehaving. It should look like the below (with fire blades):
![Screenshot 2023-07-20 141011](https://github.com/NosVladimir/KineticArchetypes/assets/32335397/a28101d5-da9b-4efb-b10e-daa959e8956f)

Just to double check, are you using Visual Adjustments 2? If you do, could you try to switch off/turn back any settings for the character to default?

You can also try to remember an empty hand, which should reset the memory, then de-activate the blades and re-activate them, so in principle you should get back the normal scimitar with correct particle effects.

**Comment by deng-tianhan** [comment]
Yes I'm using Visual Adjustments 2 and made sure to clear weapon transmogs

The particles come back after I click the appearance button

The blue eye icon appears for me when filtering for that slot. from a toybox config

**Comment by NosVladimir** [comment]
From the log, it seems for some reason the visual change happens before the off-hand blade is equipped. It is a bug from my side and I'll try to fix in the next update.

Do you at least get the main hand transmog working?

**Comment by deng-tianhan** [comment]
> Do you at least get the main hand transmog working?

Yup main hand works perfectly fine. Appreciate you looking into the matter 😃

**Comment by deng-tianhan** [comment]
Great! I just verified this is fixed in v1.0.0 👍
