### ISSUE TITLE
Esoteric blade doesn't work with rage or sohei monk

### ISSUE THREAD

**Issue by deng-tianhan** [NosVladimir/KineticArchetypes#6]
Esoteric blade 5 / Sohei 1 / duelist X
When trying to attack with negative blade or force blade, the character just hangs there. no log generated.

I also tried with instinctual warrior. during focused rage the same issue occurs.
When disabling rage, kinetic blade attack works correctly.

I suspect this might be base game issue since PFKM where kinetic blade use melee attack bonus + range damage:

- power attack reduce attack bonus, but no extra damage
- physical blade get extra damage from deadly aim, but doesn't lose attack bonus

**Comment by NosVladimir** [comment]
I've quickly tested, and from my side Esoteric blade 5 / Sohei 1 / Kinetic Duelist 7 / Barbarian 1 can ride a horse and full attack with two force blades, with main hand getting an extra attack from Sohei flurry. Not sure what's the cause for the hang...

As far as I know, power attack (and piranha strike) damage bonuses and AB penalties apply to both energy and physical kinetic blades normally, in the base game. So it's likely the no extra damage issue from power attack is a separate issue from the hang. Physical blades getting extra damage at no AB loss is also from the base game.

I suspect some other mods have interactions with rage and how power attack works?

**Comment by deng-tianhan** [comment]
hmmm... might be related to me having way too many mods enabled. 🤣 

I'll try some base game elements and update again if I discover anything useful

**Comment by NosVladimir** [comment]
Do you have Dark Codex installed? I just remembered that there is an option in it that changes blasts into spell-like, which might be disallowed by rage.

**Comment by deng-tianhan** [comment]
Great! Disabling the spell-like option allows it to be used during rage.

Energy and physical blasts still doesn't get extra damage from power attack but that's a separate issue.

Will try sohei again later

**Comment by deng-tianhan** [comment]
Disabling the spell-like option fixes sohei as well 😄
